### ISSUE TITLE
Can not find direct.h

### ISSUE THREAD

**Issue by ghost** [christofdefryn/CluVRP#2]
Hi, I have used your code for my research recently. However, when i compiled it in my ubuntu 16.04 version, there was a problem where showed **FileHandler.h:6:27: fatal error: direct.h: No such file or directory**. So can you tell me which os and libs are used when you write this code. Thank you

**Comment by Seayour** [comment]
Hi, I have used your code for my research recently. However, when i compiled it in my VS2015 version, there was a problem where showed FileHandler.h:6:27: fatal error: direct.h: No such file or directory. So can you tell me which os and libs are used when you write this code. Thank you

**Comment by christofdefryn** [comment]
@DaemonHc @Seayour 
The direct.h header is part of the windows OS, and contains the implementation for the _getcwd() function.
https://en.wikipedia.org/wiki/Direct.h

**Comment by Seayour** [comment]
您好，您的邮件我已收到，谢谢！
